### PR TITLE
0.1.9.1 release

### PR DESCRIPTION
**Pull request by raysilent**
Just new Functions/Contants definitions missing, including the most recent ones up to **15.07.28.303910**.

(Recompiled and tested with `GHC 6.10.1`)

### CODE REVIEW

**Comment by raysilent** [comment]
New Functions/Contants definitions missing, including the most recent ones up to **15.09.14.305056**.

(Recompiled and tested with ``GHC 6.10.1``)

**Comment by kyrahabattoir** [comment]
Yeah i tried to install from your fork directly, but somehow it's still not recognized, or do i have to change something else ?

**Comment by raysilent** [comment]
Let me know if that updated Readme helped you to compile the beast.

**Comment by kyrahabattoir** [comment]
Yes i followed it step by step and managed to get it to work.
One question remain, when another update happen, all i have to do is recompile LSLForge.exe? or do i have to reinstall the add on eclipse somehow?

**Comment by raysilent** [comment]
Since no Java part was touched in this patch. But if it was, then it would require updating the Eclipse addon.

**Pull request merged**
